import { type NavItemType } from "@/components/ui/navigation-menu";
import {
  clientLinks,
  executiveLinks,
  financeLinks,
  primaveraFinanceLinks,
  primaveraOpsLinks,
  primaveraSystemLinks,
  reportLinks,
  treasuryLinks,
} from "@/config/navigation";

export const moduleViews: Record<
  string,
  { title: string; eyebrow: string; description: string; links: NavItemType[] }
> = {
  ia: {
    title: "Assistente IA",
    eyebrow: "Analise assistida",
    description: "Chat Gemini com contexto PRIMAVERA, dados operacionais e graficos de apoio.",
    links: executiveLinks,
  },
  dashboard: {
    title: "Dashboard executivo",
    eyebrow: "Visão geral",
    description: "KPIs financeiros, liquidez, margem, recebimentos em atraso e sinais críticos.",
    links: executiveLinks,
  },
  "sumario-ia": {
    title: "Sumário com IA",
    eyebrow: "Visão geral",
    description: "Leitura executiva automática dos KPIs e variações do período.",
    links: executiveLinks,
  },
  alertas: {
    title: "Alertas prioritários",
    eyebrow: "Visão geral",
    description: "Riscos financeiros, operacionais e de liquidez que precisam de ação.",
    links: executiveLinks,
  },
  orcado: {
    title: "Orçado vs realizado",
    eyebrow: "Controlo financeiro",
    description: "Comparação entre orçamento, realizado e desvios por período.",
    links: executiveLinks,
  },
  "top-clientes": {
    title: "Top clientes",
    eyebrow: "Clientes",
    description: "Clientes por faturação, margem, dívida, prazo médio e concentração de risco.",
    links: clientLinks,
  },
  "top-produtos": {
    title: "Top produtos",
    eyebrow: "Produtos",
    description: "Produtos por faturação, rentabilidade, margem e impacto nos custos industriais.",
    links: primaveraOpsLinks,
  },
  dre: {
    title: "DRE e margens",
    eyebrow: "Análise financeira",
    description: "Demonstração de resultados, margens e comparação por período.",
    links: financeLinks,
  },
  rentabilidade: {
    title: "Rentabilidade",
    eyebrow: "Análise financeira",
    description: "Rentabilidade por produto, cliente, segmento e centro de custo.",
    links: financeLinks,
  },
  custos: {
    title: "Custos industriais",
    eyebrow: "Produção e custos",
    description: "Matéria-prima, transformação, energia, desvios e custos reais por ordem.",
    links: financeLinks,
  },
  breakeven: {
    title: "Break-even",
    eyebrow: "Análise financeira",
    description: "Ponto de equilíbrio por produto, linha, cliente ou centro de custo.",
    links: financeLinks,
  },
  comparar: {
    title: "Comparar períodos",
    eyebrow: "Análise financeira",
    description: "Comparação mês a mês, trimestre a trimestre e ano a ano.",
    links: financeLinks,
  },
  causas: {
    title: "Causas com IA",
    eyebrow: "Análise assistida",
    description: "Identificação de causas prováveis para quedas de margem, custos anómalos e desvios.",
    links: financeLinks,
  },
  fluxo: {
    title: "Fluxo de caixa",
    eyebrow: "Tesouraria",
    description: "Entradas, saídas e saldo projetado com dados do PRIMAVERA.",
    links: treasuryLinks,
  },
  receber: {
    title: "Contas a receber",
    eyebrow: "Tesouraria",
    description: "Faturas de clientes, aging, cobrança e detalhe do documento.",
    links: treasuryLinks,
  },
  pagar: {
    title: "Contas a pagar",
    eyebrow: "Tesouraria",
    description: "Compromissos de fornecedores, vencimentos e prioridades de pagamento.",
    links: treasuryLinks,
  },
  previsao: {
    title: "Previsão 30/60/90",
    eyebrow: "Tesouraria",
    description: "Projeção de recebimentos, pagamentos e saldo por horizonte temporal.",
    links: treasuryLinks,
  },
  liquidez: {
    title: "Risco de liquidez",
    eyebrow: "Tesouraria",
    description: "Sinais de risco no saldo projetado, atrasos de cobrança e compromissos futuros.",
    links: treasuryLinks,
  },
  bancos: {
    title: "Bancos",
    eyebrow: "Tesouraria",
    description: "Contas bancárias, movimentos, conciliação e extratos.",
    links: treasuryLinks,
  },
  clientes: {
    title: "Carteira de clientes",
    eyebrow: "Clientes",
    description: "Volume, margem média, prazo médio de pagamento e risco por cliente.",
    links: clientLinks,
  },
  aging: {
    title: "Aging de recebimentos",
    eyebrow: "Clientes",
    description: "Separação por antiguidade de dívida e concentração de risco.",
    links: clientLinks,
  },
  "risco-credito": {
    title: "Risco de crédito",
    eyebrow: "Clientes",
    description: "Score de risco, histórico de atrasos e sinais de incumprimento.",
    links: clientLinks,
  },
  historico: {
    title: "Histórico de pagamentos",
    eyebrow: "Clientes",
    description: "Pagamentos, atrasos, liquidações e comportamento financeiro por cliente.",
    links: clientLinks,
  },
  concentracao: {
    title: "Concentração de risco",
    eyebrow: "Clientes",
    description: "Peso de clientes no volume, dívida, margem e risco de cobrança.",
    links: clientLinks,
  },
  comunicacoes: {
    title: "Comunicações",
    eyebrow: "Clientes",
    description: "E-mails, chamadas, lembretes e histórico de contacto de cobrança.",
    links: clientLinks,
  },
  relatorios: {
    title: "Relatórios financeiros",
    eyebrow: "Relatórios",
    description: "DRE, balanço, fluxo de caixa e rentabilidade para exportação.",
    links: reportLinks,
  },
  exportacoes: {
    title: "Exportações",
    eyebrow: "Relatórios",
    description: "Exportação para PDF, Excel e pacotes de reporting executivo.",
    links: reportLinks,
  },
  agendados: {
    title: "Relatórios agendados",
    eyebrow: "Relatórios",
    description: "Relatórios periódicos com envio automático e histórico.",
    links: reportLinks,
  },
  thresholds: {
    title: "Thresholds",
    eyebrow: "Alertas",
    description: "Limites de margem, caixa, atraso, custos e orçamento.",
    links: reportLinks,
  },
  acoes: {
    title: "Ações tomadas",
    eyebrow: "Alertas",
    description: "Histórico de ações, responsáveis, datas e resultados.",
    links: reportLinks,
  },
  simulador: {
    title: "Simulador de cenários",
    eyebrow: "Planeamento",
    description: "Simulação de preço, custos, investimento e perda/ganho de clientes.",
    links: reportLinks,
  },
  bas: {
    title: "Base Aplicacional",
    eyebrow: "BAS",
    description: "Entidades, artigos, armazéns, tabelas base e dados mestre do PRIMAVERA.",
    links: primaveraSystemLinks,
  },
  cbl: {
    title: "Contabilidade",
    eyebrow: "CBL",
    description: "Plano de contas, movimentos contabilísticos, balancetes e mapas.",
    links: primaveraFinanceLinks,
  },
  cct: {
    title: "Contas Correntes",
    eyebrow: "CCT",
    description: "Pendentes de clientes/fornecedores, liquidações, aging e cobrança.",
    links: treasuryLinks,
  },
  cmp: {
    title: "Compras",
    eyebrow: "CMP",
    description: "Documentos de compra, fornecedores, custos e compromissos.",
    links: primaveraFinanceLinks,
  },
  crm: {
    title: "CRM",
    eyebrow: "CRM",
    description: "Contactos, oportunidades, propostas e comunicações comerciais.",
    links: primaveraOpsLinks,
  },
  eap: {
    title: "Equipamentos e Activos",
    eyebrow: "EAP",
    description: "Equipamentos, activos, manutenção e imobilizado operacional.",
    links: primaveraSystemLinks,
  },
  erp: {
    title: "ERP",
    eyebrow: "ERP",
    description: "Núcleo ERP, documentos transversais e ligação entre módulos.",
    links: primaveraSystemLinks,
  },
  epk: {
    title: "EyePeak",
    eyebrow: "EPK",
    description: "Componente EyePeak detetado no PRIMAVERA, para operação e integração específica.",
    links: primaveraSystemLinks,
  },
  fil: {
    title: "Filiais",
    eyebrow: "FIL",
    description: "Filiais, empresas e estrutura multi-entidade.",
    links: primaveraSystemLinks,
  },
  int: {
    title: "Internos",
    eyebrow: "INT",
    description: "Operações internas e documentos transversais do PRIMAVERA.",
    links: primaveraSystemLinks,
  },
  gpr: {
    title: "Produção",
    eyebrow: "GPR",
    description: "Ordens de fabrico, componentes, tempos e custos previstos/reais.",
    links: primaveraOpsLinks,
  },
  inv: {
    title: "Inventário",
    eyebrow: "INV",
    description: "Artigos, armazéns, movimentos de stock, stock atual e custeio.",
    links: primaveraOpsLinks,
  },
  prj: {
    title: "Projetos e Serviços",
    eyebrow: "PRJ",
    description: "Projetos, serviços, WBS, centros de custo e rentabilidade.",
    links: primaveraOpsLinks,
  },
  mob: {
    title: "Mobile",
    eyebrow: "MOB",
    description: "Componente mobile instalado, sincronização e operação fora do ERP desktop.",
    links: primaveraSystemLinks,
  },
  pcm: {
    title: "Gestão de Contratos",
    eyebrow: "PCM",
    description: "Contratos, serviços recorrentes e obrigações associadas.",
    links: primaveraSystemLinks,
  },
  rhp: {
    title: "Recursos Humanos",
    eyebrow: "RHP",
    description: "Funcionários, custos de pessoal e informação de RH.",
    links: primaveraOpsLinks,
  },
  stp: {
    title: "Serviços Técnicos",
    eyebrow: "STP",
    description: "Serviços técnicos, contratos, equipamentos e intervenções.",
    links: primaveraOpsLinks,
  },
  tes: {
    title: "Tesouraria",
    eyebrow: "TES",
    description: "Contas bancárias, movimentos, caixa, recebimentos e pagamentos.",
    links: treasuryLinks,
  },
  tte: {
    title: "Track and Trace",
    eyebrow: "TTE",
    description: "Transações eletrónicas e rastreabilidade documental.",
    links: primaveraSystemLinks,
  },
  vnd: {
    title: "Vendas",
    eyebrow: "VND",
    description: "Documentos de venda, clientes, vendedores, faturação e margem.",
    links: primaveraFinanceLinks,
  },
  webapi: {
    title: "Web API Cegid",
    eyebrow: "Integração",
    description: "Estado da Web API instalada e ligação alternativa via SQL local.",
    links: primaveraSystemLinks,
  },
};
